### ISSUE TITLE
配置好启动报错。

### ISSUE THREAD

**Issue by Neo110** [tomoya92/pybbs#28]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:851) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]

**Comment by TakWolf** [comment]
JPA工厂创建失败，检查一下数据库相关的配置是否正确

**Comment by Neo110** [comment]
配置没有问题

**Comment by Neo110** [comment]
jpa:
    database: mysql
    show-sql: true
    hibernate:   ？？？？？？ 这个配置什么呢 ？
    ddl-auto: update

**Comment by tomoya92** [comment]
>  hibernate: ？？？？？？ 这个配置什么呢 ？
    ddl-auto: update

这个是帮你生成表结构的

**Comment by Neo110** [comment]
2016-11-03 16:13:48.692  WARN 63479 --- [nio-8080-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: java.lang.IllegalArgumentException: Cannot find cache named 'userCache' for Builder[public cn.tomoya.module.user.entity.User cn.tomoya.module.user.service.UserService.findByUsername(java.lang.String)] caches=[userCache] | key=''userName_'+#username' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'
2016-11-03 16:13:48.719  INFO 63479 --- [nio-8080-exec-2] cn.tomoya.interceptor.CommonInterceptor  : 0:0:0:0:0:0:0:1|/register|_csrf=b5b52c58-7c8e-4f3d-8846-0efab6741fa1|username=neo|password=123456|excutetime=40ms
2016-11-03 16:14:12.849  INFO 63479 --- [nio-8080-exec-9] cn.tomoya.interceptor.CommonInterceptor  : 0:0:0:0:0:0:0:1|/register|excutetime=3ms
2016-11-03 16:14:15.110  WARN 63479 --- [nio-8080-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: java.lang.IllegalArgumentException: Cannot find cache named 'userCache' for Builder[public cn.tomoya.module.user.entity.User cn.tomoya.module.user.service.UserService.findByUsername(java.lang.String)] caches=[userCache] | key=''userName_'+#username' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'
2016-11-03 16:14:15.112  INFO 63479 --- [nio-8080-exec-3] cn.tomoya.interceptor.CommonInterceptor  : 0:0:0:0:0:0:0:1|/register|_csrf=b5b52c58-7c8e-4f3d-8846-0efab6741fa1|username=neo|password=123456|excutetime=4ms


注册 和登录都报   Cannot find cache named 'userCache'   错误是缓存的问题？

**Comment by TakWolf** [comment]
这个问题怎么解决的？

**Comment by tomoya92** [comment]
@TakWolf 他没更新代码，以前配置的缓存有问题
