### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by yyl2016** [tomoya92/pybbs#43]
我在tomcat上部署pybbs，启动tomcat并访问，出现”啊哦，服务器出错了~~“这样的错误，是怎么回事啊？

**Comment by tomoya92** [comment]
控制台报什么错了

**Comment by yyl2016** [comment]
我是直接将pybbs2.3的war包部署到tomcat上的，后来试一直不行，就换成pybbs2.2版本的了，部署2.2版本的，启动tomcat时报以下错误：
二月 08, 2017 10:22:23 上午 org.apache.catalina.startup.HostConfig deployWAR
信息: Deploying web application archive D:\soft\apache-tomcat-7.0.40\webapps\jfinalbbs.war
二月 08, 2017 10:22:24 上午 org.apache.catalina.loader.WebappClassLoader validateJarFile
信息: validateJarFile(D:\soft\apache-tomcat-7.0.40\webapps\jfinalbbs\WEB-INF\lib\servlet-api-3.0-alpha-1.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/servlet/Servlet.class
二月 08, 2017 10:22:27 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-apr-8080"]
二月 08, 2017 10:22:27 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["ajp-apr-8009"]
二月 08, 2017 10:22:27 上午 org.apache.catalina.startup.Catalina start
信息: Server startup in 3174 ms
说某个jar没load，但我看项目中的lib下，那个包是存在的。后来又换了一个tomcat报
”Shiro environment initialization failed”这样的错误，不知道怎么回事各种稀奇古怪的错误。

**Comment by yyl2016** [comment]
那个pybbs2.3版本的除了需要安装redis还需要安装其它东西吗？

**Comment by yyl2016** [comment]
我现在弄2.3版本的，启动tomcat报下面的错误，不知道是什么情况，数据库是存在的。
[ERROR]-[Thread: Druid-ConnectionPool-Create-782109023]-[com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run()]: create connection error, url: jdbc:mysql://localhost/pybbs?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:951)
   at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1717)
   at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1276)
   at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2395)
   at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2428)
   at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2213)
   at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:797)
   at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
   at sun.reflect.GeneratedConstructorAccessor34.newInstance(Unknown Source)
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
   at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
   at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
   at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:148)
   at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:785)
   at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
   at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:211)
   at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
   at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1410)
   at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464)
   at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1969)

**Comment by yyl2016** [comment]
还有一个错误是：
Exception in thread "cron4j::scheduler[1faea40450402c7550fed2070000015a1d47677a1763b6de]::launcher[1faea40450402c7516f745a70000015a1d47a9024bbc2a96]" java.lang.NoClassDefFoundError: it/sauronsoftware/cron4j/TaskTable
   at it.sauronsoftware.cron4j.MemoryTaskCollector.getTasks(Unknown Source)
   at it.sauronsoftware.cron4j.LauncherThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: it.sauronsoftware.cron4j.TaskTable
   at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
   at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
   ... 2 more
Exception in thread "cron4j::scheduler[1faea4043b4445bf5c7ebf5a0000015a1d2ee7be14a5ec26]::launcher[1faea4043b4445bf4586693a0000015a1d47a901365aab4e]" java.lang.NoClassDefFoundError: it/sauronsoftware/cron4j/TaskTable
   at it.sauronsoftware.cron4j.MemoryTaskCollector.getTasks(Unknown Source)
   at it.sauronsoftware.cron4j.LauncherThread.run(Unknown Source)

**Comment by tomoya92** [comment]
上面是mysql数据库用户名密码错了，下面的是没有jar包，具体你百度吧
