### ISSUE TITLE
怎么在我的开发机上用Github登录？

### ISSUE THREAD

**Issue by linkerlin** [tomoya92/pybbs#9]
我申请了Github的client_id和client_secert,也配置了。
但是没有办法在开发机接受github的callback啊？

**Comment by tomoya92** [comment]
开发环境的话，需要想办法让外网能访问到，常用办法可以用ngrok或者花生壳映射一个域名，然后把github里的callback地址的域名改下就可以了

也可以看看这个话题来配置登录后的开发环境 http://bbs.tomoya.cn/t/17

**Comment by linkerlin** [comment]
晕，这个有点麻烦啊。
是不是可以做个后门什么的？

**Comment by tomoya92** [comment]
没有做后门
因为没有本地登录，所以只能这样来处理

**Comment by linkerlin** [comment]
要不开发模式的时候，还是增加一个随意指定登录用户的页面吧？
生产环境可以作为模拟登录的功能，也蛮方便的。

**Comment by tomoya92** [comment]
本地开发登录后的功能确实有点麻烦，但是，都会自己开发了，难道还不会往数据库里写一条测试数据吗，这功能对pybbs没有一点用处，只是方便开发而已，所以不会增加的，方法都整理出来了，开发者自己按照话题里的步骤来增加一条数据即可，也是非常简单的事，见谅！

**Comment by linkerlin** [comment]
嗯，我按照帖子里的方案可以登录了。
但是登录后不能创建话题，是不是还要设置权限？
我的用户uid在权限表中有对应记录，udi=1 rid=1。

**Comment by tomoya92** [comment]
@linkerlin 提示什么信息了吗？

**Comment by linkerlin** [comment]
没有，没找到创建话题的地方。但是用户是登录成了。

**Comment by tomoya92** [comment]
@linkerlin 清除一下缓存，还不行，重启一下tomcat，还不行，看看用户管理里面你的用户是不是被禁了

**Comment by linkerlin** [comment]
有道理，那个is_block字段应该配置成什么值？

**Comment by linkerlin** [comment]
isblock我配置的是0

**Comment by tomoya92** [comment]
@linkerlin 1是true 被禁，0 false正常用户

**Comment by linkerlin** [comment]
积分板可以出来，个人页面也可以。
首页无法找到创建话题的地方。

**Comment by linkerlin** [comment]
如图
![fullscreen_7_11_16__17_46](https://cloud.githubusercontent.com/assets/37062/16726575/802a7288-478f-11e6-9c2f-7a93b7dc589f.jpg)

**Comment by tomoya92** [comment]
@linkerlin 你这根本就没登录，cookie里的值一看就不对，你在好好看看我发你的那个本地登录的文章

**Comment by linkerlin** [comment]
我的access_token设置的是一个字符 x
cookie的值取自        System.out.println(getEncryptionToken("x"));
的输出。

**Comment by tomoya92** [comment]
@linkerlin 好吧，，那你user表里的的token设置的是啥？也要是x，才可以

**Comment by linkerlin** [comment]
是的 。

**Comment by tomoya92** [comment]
@linkerlin cookie里的域名直接localhost就可以了，不用带端口

**Comment by linkerlin** [comment]
如图
![fullscreen_7_11_16__17_58](https://cloud.githubusercontent.com/assets/37062/16726876/1576e938-4791-11e6-9b34-01691a974a51.jpg)

**Comment by linkerlin** [comment]
端口是firebug强制加上的。改了又会加回去。

**Comment by linkerlin** [comment]
捐赠了100元，求解决问题。

**Comment by tomoya92** [comment]
@linkerlin 你换成chrome在试试，我记得带端口是取不到数据的，刚才我试着在chrome里把端口带上，结果cookie直接被清了。。

**Comment by tomoya92** [comment]
@linkerlin 感谢捐赠！！

**Comment by linkerlin** [comment]
还是希望能开发一个模拟登陆的功能，对整个项目的推广有好处。

**Comment by linkerlin** [comment]
上面的那个问题定位了，应该就是cookie的端口号的问题。

**Comment by linkerlin** [comment]
换句话说，如果网站部署在 localhost:8080, cookie也必须绑定到localhost，不带8080。
感觉这里面有什么漏洞存在。
不知道是jfinal的问题,还是pybbs的问题？

**Comment by tomoya92** [comment]
@linkerlin 嗯，找到原因就好，模拟本地登录还是不会开发的，晚上我回去把话题再完善一下，可以不借助浏览器cookie插件来解决

**Comment by linkerlin** [comment]
发布第一个话题的时出错了：
[WARN]-[Thread: qtp1208417271-16]-[com.jfinal.core.ActionHandler.handle()]: 404 Action Not Found: /solr/pybbs/update?wt=javabin&version=2

2016-07-11 18:54:48
[ERROR]-[Thread: qtp1208417271-17]-[com.jfinal.core.ActionHandler.handle()]: /t/create
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8080/solr/pybbs: Expected mime type application/octet-stream but got text/html. <!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <title>未知地址</title>
</head>
<body>
<script type="text/javascript" src="http://www.qq.com/404/search_children.js" charset="utf-8" homePageUrl="/" homePageName="回到我的主页"></script>
</body>
</html>
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:545)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:173)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:138)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:152)
	at cn.tomoya.utils.SolrUtil.indexTopic(SolrUtil.java:90)
	at cn.tomoya.module.topic.TopicController.create(TopicController.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at cn.tomoya.interceptor.UserStatusInterceptor.intercept(UserStatusInterceptor.java:30)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at cn.tomoya.interceptor.UserInterceptor.intercept(UserInterceptor.java:37)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at cn.tomoya.interceptor.CommonInterceptor.intercept(CommonInterceptor.java:59)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Sql: select id from pybbs_notification where `read` = ? and target_author = ?
Sql: insert into `pybbs_topic`(`view`, `in_time`, `tab`, `top`, `author`, `isdelete`, `title`, `last_reply_time`, `show_status`, `reply_count`, `good`, `content`) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Sql: select * from pybbs_topic_append where isdelete = ? and tid = ? order by in_time

2016-07-11 18:54:53
[WARN]-[Thread: qtp1208417271-18]-[com.jfinal.core.ActionHandler.handle()]: 404 Action Not Found: /solr/pybbs/update?wt=javabin&version=2

2016-07-11 18:54:53
[ERROR]-[Thread: qtp1208417271-13]-[com.jfinal.core.ActionHandler.handle()]: /t/create
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8080/solr/pybbs: Expected mime type application/octet-stream but got text/html. <!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <title>未知地址</title>
</head>
<body>
<script type="text/javascript" src="http://www.qq.com/404/search_children.js" charset="utf-8" homePageUrl="/" homePageName="回到我的主页"></script>
</body>
</html>
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:545)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:173)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:138)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:152)
	at cn.tomoya.utils.SolrUtil.indexTopic(SolrUtil.java:90)
	at cn.tomoya.module.topic.TopicController.create(TopicController.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
	at cn.tomoya.interceptor.UserStatusInterceptor.intercept(UserStatusInterceptor.java:30)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at cn.tomoya.interceptor.UserInterceptor.intercept(UserInterceptor.java:37)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at cn.tomoya.interceptor.CommonInterceptor.intercept(CommonInterceptor.java:59)
	at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
	at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
	at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

**Comment by linkerlin** [comment]
似乎是强制必须启用solr?

**Comment by tomoya92** [comment]
@linkerlin 不用，看看配置文件，里面有开关

**Comment by tomoya92** [comment]
@linkerlin 参见这篇文章 http://bbs.tomoya.cn/t/34
